# Generated by Django 4.2 on 2023-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.TextField()),
                ('why', models.TextField()),
                ('resume', models.FileField(upload_to='pdf_documents/')),
                ('date', models.DateField()),
            ],
        ),
    ]
