# Generated by Django 4.2 on 2023-05-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourHR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='resume/'),
        ),
    ]
